# Generated by Django 6.0.1 on 2026-01-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_playbackhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedLyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "lrc_content",
                    models.TextField(help_text="LRC format lyrics with timestamps"),
                ),
                ("source", models.CharField(default="jiosaavn", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Synced Lyrics",
            },
        ),
        migrations.AddField(
            model_name="playbackhistory",
            name="artist",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="playbackhistory",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playbackhistory",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="CurrentlyPlaying",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("started_at", models.DateTimeField(auto_now=True)),
                ("is_playing", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currently_playing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Currently Playing",
            },
        ),
        migrations.CreateModel(
            name="ListeningStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_listen_date", models.DateField(blank=True, null=True)),
                ("total_days_listened", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listening_streak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["follower", "-created_at"],
                        name="music_frien_followe_04c69b_idx",
                    ),
                    models.Index(
                        fields=["following", "-created_at"],
                        name="music_frien_followi_a69b3c_idx",
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("total_minutes", models.IntegerField(default=0)),
                ("total_songs", models.IntegerField(default=0)),
                ("unique_artists", models.IntegerField(default=0)),
                ("top_songs", models.JSONField(default=list)),
                ("top_artists", models.JSONField(default=list)),
                ("genre_distribution", models.JSONField(default=dict)),
                ("hourly_distribution", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Monthly Stats",
                "indexes": [
                    models.Index(
                        fields=["user", "-year", "-month"],
                        name="music_month_user_id_a790f3_idx",
                    )
                ],
                "unique_together": {("user", "year", "month")},
            },
        ),
    ]
